### PR TITLE
Initial index.html structure setup

### PR DESCRIPTION
**Pull request by calvincurry22**
#Changes
*Added semantic container elements in index.html

#Testing 
*Open file in vsCode
*Verify that all container elements are present in index.html

### CODE REVIEW

**Review by durrjp — APPROVED** [review]
all containers needed are present 👍

**Review by Keartroth — APPROVED** [review]
Looks good! Ship it. 👍

**Review by iparkerhodge — APPROVED** [review]
👍

**Review by ygitore — APPROVED** [review]
👍 looks great

**Pull request merged**
